image: python:3.6
before_script:
    - python3 -m venv venv
    - . venv/bin/activate
    - pip install -r requirements.txt


test:
    script:
        - . venv/bin/activate
        - pytest -v --cov=openweather
    